### ISSUE TITLE
Docker cloud support

### ISSUE THREAD

**Issue by nanek** [scoutapp/docker-scout#4]
Any tips for getting this to run on cloud.docker.com? It is possible to set the `account_key` as an environment variable instead of mounting a volume for the yml file?

**Comment by itsderek23** [comment]
Good question!

scoutd will actually automatically read environment vars. [Here's the list of possible environment vars](https://github.com/scoutapp/scoutd/blob/master/scoutd/config.go#L139) straight from the source.
